version: '3'
services:
  app:
    build:
      context: ./frontend
      dockerfile: Dockerfile.development
    ports:
      - 3000:3000
    volumes:
      - ./frontend/:/app/
    command: bash -c 'npm run dev'
