version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.development
    ports:
      - 5173:5173
    volumes:
      - ./frontend/:/app/
    command: bash -c 'npm run dev'

  backend:
    env_file:
      - ./backend/.env
    build:
      context: ./backend
      dockerfile: Dockerfile.development
    ports:
      - 3000:3000
    volumes:
      - ./backend/:/app/
    command: bash -c "rm -rf /app/tmp/pids/server.pid &&
                      rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./tmp/db/:/var/lib/postgres/data/
